config/routes.rb
Rails.application.routes.draw do

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get "/books" => "books#index", as: 'books'
  get "/books/new" => "books#new", as: 'new_book'
  get "/books/overdue" => "books#overdue", as: 'overdue'
  get "/books/search" => "books#search", as: 'search'
  get "/books/:id" => "books#show", as: 'book'
  post "/books" => "books#create"
  get "books/:id/edit" => "books#edit", as: 'edit_book'


  get "/users" => "users#index", as: 'users'
  #get "/users/new" => "users#new", as: 'new_user'

  get "/authors" => "authors#index", as: 'authors'
  get "/authors/:id" => "authors#show", as: 'author'
  #get "/authors/new" => "authors#new", as: 'new_author'

  get "/reservations" => "reservations#index", as: 'reservations'


  resources :books do
      get 'page/:page', :action => :index, :on => :collection
  end

  root 'sessions#new'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
  validates :name, :dob, :nationality, :biography, :image_url, presence: true
  validates :biography, length: {minimum: 18}
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  validates :isbn, :title, :abstract ,:pages, :genre, :published_on, :total_in_library, :author, presence:true
  validates :abstract, length: {minimum: 15}
  validates :pages, :total_in_library,
    numericality:{only_integer:true, greater_than_or_equal_to:0}

  has_many :reservations, dependent: :destroy
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reservations, dependent: :destroy
  has_many :books, through: :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController


  before_action :set_author, only: [ :show ]

  def index
    @available_at = Time.now
    @authors = Author.order(:name).page(params[:page])
  end

  def new
    @author = Author.new
  end

  def show
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [ :show, :edit, :update, :destroy ]
  before_action :set_available_time, only: [:index, :search]

  def index
    @books = Book.order(:title).page(params[:page])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: "#{@book.title} was created!"
    else
      render :new
    end
  end

  def show
    @author = @book.author
  end

  def new
    @book = Book.new
  end

  def overdue
    #TODO: Figure out which books are overdue and return them to display on the form.
  end

  def search
    #TODO: Implement Search
    @books = Book.order(:title).page(params[:page])

    #@books = Book.search(params[:search]) THIS didn't work

  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: "#{@book.title} was updated!"
    else
      render :new
    end
  end


  def destroy
    @book.destroy
    redirect_to books_url
  end




  private

  def book_params
    params.require(:book).permit(:title, :pages, :isbn, :author, :author_id, :genre, :abstract, :image_cover_url, :created_at, :updated_at, :published_on, :total_in_library)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def set_available_time
    @available_at = Time.now
  end

end

app/controllers/reservation_controller.rb
class ReservationsController < ApplicationController

  def new
    @reservation = Reservation.new
  end


end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new
    @reservation = Reservation.new
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(user_id: params[:user_id])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.user_id
      redirect_to books_path
    else
      redirect_to sessions_new_path, notice: 'Login Failed!'
    end
    end


  def destroy
    session[:user_id] = nil
    redirect_to sessions_destroy_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController






  def new
   #@user = User.new
   @user = User.new

  end


  def create
    @user = 'TEMP'
  end

  def check_login

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def formatted_time(time)
    time.strftime("%B %d, %Y at %l:%M %p")
  end

  def format_average_stars(book)
    average = book.average_stars
    if average
      pluralize(number_with_precision(average, precision: 1), 'star')
    else
      'No reviews'
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>
  <%= page_entries_info @authors %>
  <ol>
    <% @authors.each do |author| %>
      <li>
        <%= link_to(author.name, author) %><br/>
      </li>
    <% end %>
  </ol>

<%= paginate @authors %>

app/views/authors/show.html.erb
<% content_for :author, @author.name %>
<article class="author">
  <header>
    <h2> <%= @author.name %> </h2>
  </header>

  <p><label>Nationality:</label> <%= @author.nationality %></p>
  <p><label>DOB:</label> <%= @author.dob %></p>
  <p><label>Awards:</label> <%= @author.awards %></p>
  <p><label>Biography:</label> <%= @author.biography %></p>
  <p> <%= image_tag(@author.image_url, height: '120') %></p>

</article>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
<%= render 'shared/validation_errors', object: @book %>
<%= f.label :isbn %> <%= f.text_field :isbn, autofocus: true %><br />
<%= f.label :title %> <%= f.text_field :title %><br />
<%= f.label :author_id %> <%= f.collection_select :author_id, Author.all, :id, :name %><br />
<%= f.label :genre %> <%= f.text_field :genre %><br />
<%= f.label :abstract %> <%= f.text_field :abstract %><br />
<%= f.label :pages %> <%= f.text_field :pages %><br />
<%= f.label :image_cover_url %> <%= f.text_field :image_cover_url %><br />
<%= f.label :published_on %> <%= f.date_select :published_on %><br />
<%= f.label :total_in_library %> <%= f.text_field :total_in_library %><br />
<%= f.label :created_at %> <%= f.text_field :created_at %><br />
<%= f.label :updated_at %> <%= f.text_field :updated_at %><br />
<p>
<%= f.submit %>
<%= link_to 'Cancel', books_path %>
</p>
<% end %>

app/views/books/_results.html.erb
<br>
<%= text_field_tag :search_terms %><%= link_to 'Search', search_path %>




<% form_tag search_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>



<br>
<br>
<p>Available as <%= formatted_time(@available_at) %></p>
  <%= page_entries_info @books %>
  <ol>
    <% @books.each do |book| %>
      <li>
        <%= link_to(book.title, book) %> by
        <%= link_to(book.author.name, book.author) %><br/>
      </li>
    <% end %>
  </ol>

<%= paginate @books %>

app/views/books/edit.html.erb
<h1>Editing <% @book.title %></h1>
<%= render 'form' %>

app/views/books/index.html.erb
<h1>All Books</h1>
<%= render 'results' %>

app/views/books/new.html.erb
<h1>Create a New Book</h1>
<%= render 'form' %>

app/views/books/search.html.erb
<h1>Search Results</h1>
<%= render 'results' %>

app/views/books/show.html.erb
<% content_for :title, @book.title %>
<article class="book">
  <header>
    <h2> <%= @book.title %> </h2>
  </header>

  <p><label>ISBN:</label> <%= @book.isbn %></p>
  <p><label>Title:</label> <%= @book.title %></p>
  <p><label>Author:</label> <%= link_to(@book.author.name, @book.author) %></p>
  <p><label>Genre:</label> <%= @book.genre %></p>
  <p><label>Abstract:</label> <%= @book.abstract %></p>
  <p><label>Pages:</label> <%= number_with_delimiter(@book.pages) %></p>
  <p> <%= image_tag(@book.image_cover_url, height: '120') %></p>
  <p><label>Published On:</label> <%= @book.published_on %></p>
  <p><label>Total In Library:</label> <%= @book.total_in_library %></p>
  <p><label>Created At:</label> <%= @book.created_at %></p>
  <p><label>Updated At:</label> <%= @book.updated_at %></p>

</article>

  <%= link_to 'Edit', edit_book_path(@book) %>
  <%= button_to 'Delete', @book,
  method: :delete,
  data: { confirm: 'Are you sure?' } %>

app/views/layouts/_admin.html.erb
<p>
  <%= link_to 'New Book', new_book_path %>
</p>
<p>
  <%= link_to 'Overdue Books', overdue_path %>
</p>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
  <h1>Library</h1>
</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div class="panel panel-primary">
    <div class="panel-heading">
     <h3 class="panel-title">Navigation</h3>
    </div>
    <div class="panel-body">
      <p>
        <%= link_to 'All Books', books_path %>
      </p>
      <p>
        <%= link_to 'Authors', authors_path %>
      </p>
      <p>
        <%= link_to 'My Reservations', reservations_path %>
      </p>
      <%= render '/layouts/admin' %>
      <p>
        <%= link_to 'Logout', sessions_destroy_path %>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Books <%= yield :title %></title>
<%= stylesheet_link_tag "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= render '/layouts/header' %>
</div>
<div class="container">
<div class="col-xs-9">
   <%= render '/shared/flashes' %>
    <%= yield %>
</div>
<div class="col-xs-3">
<%= render '/layouts/sidebar' %>
</div>
</div>
<%= render '/layouts/footer' %>
</body>
</html>

app/views/reservations/index.html.erb
<h1>Reservations</h1>

app/views/shared/_flashes.html.erb
<% if flash.present? %>
<div id="flashes">
<% flash.each do |key, value| %>
<p class="flash <%= key %>"><%= value %></p>
<% end %>
</div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  Oops! The <%= object.class.name.humanize.downcase %> could not be saved.<br />
  Correct the following <%= pluralize(object.errors.count, "error") %>:
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/_form.html.erb
  <%= label_tag :user_id, 'Username: ' %><br>
  <%= text_field_tag :user_id %><br>

  <%= label_tag :password_digest, 'Password: ' %><br>
  <%= password_field_tag :password_digest %><br>

  <%= submit_tag 'Login' %>

app/views/users/index.html.erb
<h1>Logout</h1>